// Code generated by MockGen. DO NOT EDIT.
// Source: ./turboswap/interface.go
//
// Generated by this command:
//
//	mockgen -source=./turboswap/interface.go -destination=./turboswap/mock.go -package=turboswap
//

// Package turboswap is a generated GoMock package.
package turboswap

import (
	context "context"
	reflect "reflect"

	store "github.com/kehiy/RoboPac/store"
	gomock "go.uber.org/mock/gomock"
)

// MockITurboSwap is a mock of ITurboSwap interface.
type MockITurboSwap struct {
	ctrl     *gomock.Controller
	recorder *MockITurboSwapMockRecorder
}

// MockITurboSwapMockRecorder is the mock recorder for MockITurboSwap.
type MockITurboSwapMockRecorder struct {
	mock *MockITurboSwap
}

// NewMockITurboSwap creates a new mock instance.
func NewMockITurboSwap(ctrl *gomock.Controller) *MockITurboSwap {
	mock := &MockITurboSwap{ctrl: ctrl}
	mock.recorder = &MockITurboSwapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITurboSwap) EXPECT() *MockITurboSwapMockRecorder {
	return m.recorder
}

// AddDiscountCode mocks base method.
func (m *MockITurboSwap) AddDiscountCode(ctx context.Context, party *store.TwitterParty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDiscountCode", ctx, party)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDiscountCode indicates an expected call of AddDiscountCode.
func (mr *MockITurboSwapMockRecorder) AddDiscountCode(ctx, party any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDiscountCode", reflect.TypeOf((*MockITurboSwap)(nil).AddDiscountCode), ctx, party)
}

// GetDiscountCodeStatus mocks base method.
func (m *MockITurboSwap) GetDiscountCodeStatus(ctx context.Context, pubKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscountCodeStatus", ctx, pubKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDiscountCodeStatus indicates an expected call of GetDiscountCodeStatus.
func (mr *MockITurboSwapMockRecorder) GetDiscountCodeStatus(ctx, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscountCodeStatus", reflect.TypeOf((*MockITurboSwap)(nil).GetDiscountCodeStatus), ctx, pubKey)
}
