// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/interface.go -destination=./internal/repository/mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	entity "github.com/pagu-project/Pagu/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIDatabase is a mock of IDatabase interface.
type MockIDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseMockRecorder
	isgomock struct{}
}

// MockIDatabaseMockRecorder is the mock recorder for MockIDatabase.
type MockIDatabaseMockRecorder struct {
	mock *MockIDatabase
}

// NewMockIDatabase creates a new mock instance.
func NewMockIDatabase(ctrl *gomock.Controller) *MockIDatabase {
	mock := &MockIDatabase{ctrl: ctrl}
	mock.recorder = &MockIDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabase) EXPECT() *MockIDatabaseMockRecorder {
	return m.recorder
}

// AddFaucet mocks base method.
func (m *MockIDatabase) AddFaucet(f *entity.PhoenixFaucet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFaucet", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFaucet indicates an expected call of AddFaucet.
func (mr *MockIDatabaseMockRecorder) AddFaucet(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFaucet", reflect.TypeOf((*MockIDatabase)(nil).AddFaucet), f)
}

// AddNotification mocks base method.
func (m *MockIDatabase) AddNotification(v *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNotification", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNotification indicates an expected call of AddNotification.
func (mr *MockIDatabaseMockRecorder) AddNotification(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNotification", reflect.TypeOf((*MockIDatabase)(nil).AddNotification), v)
}

// AddUser mocks base method.
func (m *MockIDatabase) AddUser(u *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockIDatabaseMockRecorder) AddUser(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockIDatabase)(nil).AddUser), u)
}

// AddValidator mocks base method.
func (m *MockIDatabase) AddValidator(arg0 *entity.Validator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddValidator", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddValidator indicates an expected call of AddValidator.
func (mr *MockIDatabaseMockRecorder) AddValidator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddValidator", reflect.TypeOf((*MockIDatabase)(nil).AddValidator), arg0)
}

// AddVoucher mocks base method.
func (m *MockIDatabase) AddVoucher(v *entity.Voucher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVoucher", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVoucher indicates an expected call of AddVoucher.
func (mr *MockIDatabaseMockRecorder) AddVoucher(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVoucher", reflect.TypeOf((*MockIDatabase)(nil).AddVoucher), v)
}

// AddZealyUser mocks base method.
func (m *MockIDatabase) AddZealyUser(u *entity.ZealyUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddZealyUser", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddZealyUser indicates an expected call of AddZealyUser.
func (mr *MockIDatabaseMockRecorder) AddZealyUser(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddZealyUser", reflect.TypeOf((*MockIDatabase)(nil).AddZealyUser), u)
}

// CanGetFaucet mocks base method.
func (m *MockIDatabase) CanGetFaucet(user *entity.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanGetFaucet", user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanGetFaucet indicates an expected call of CanGetFaucet.
func (mr *MockIDatabaseMockRecorder) CanGetFaucet(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanGetFaucet", reflect.TypeOf((*MockIDatabase)(nil).CanGetFaucet), user)
}

// ClaimVoucher mocks base method.
func (m *MockIDatabase) ClaimVoucher(id uint, txHash string, claimer uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimVoucher", id, txHash, claimer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClaimVoucher indicates an expected call of ClaimVoucher.
func (mr *MockIDatabaseMockRecorder) ClaimVoucher(id, txHash, claimer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimVoucher", reflect.TypeOf((*MockIDatabase)(nil).ClaimVoucher), id, txHash, claimer)
}

// GetAllZealyUser mocks base method.
func (m *MockIDatabase) GetAllZealyUser() ([]*entity.ZealyUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllZealyUser")
	ret0, _ := ret[0].([]*entity.ZealyUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllZealyUser indicates an expected call of GetAllZealyUser.
func (mr *MockIDatabaseMockRecorder) GetAllZealyUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllZealyUser", reflect.TypeOf((*MockIDatabase)(nil).GetAllZealyUser))
}

// GetPendingMailNotification mocks base method.
func (m *MockIDatabase) GetPendingMailNotification() (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingMailNotification")
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingMailNotification indicates an expected call of GetPendingMailNotification.
func (mr *MockIDatabaseMockRecorder) GetPendingMailNotification() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingMailNotification", reflect.TypeOf((*MockIDatabase)(nil).GetPendingMailNotification))
}

// GetUserByApp mocks base method.
func (m *MockIDatabase) GetUserByApp(appID entity.AppID, callerID string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByApp", appID, callerID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByApp indicates an expected call of GetUserByApp.
func (mr *MockIDatabaseMockRecorder) GetUserByApp(appID, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByApp", reflect.TypeOf((*MockIDatabase)(nil).GetUserByApp), appID, callerID)
}

// GetValidator mocks base method.
func (m *MockIDatabase) GetValidator(arg0 uint) (entity.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidator", arg0)
	ret0, _ := ret[0].(entity.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidator indicates an expected call of GetValidator.
func (mr *MockIDatabaseMockRecorder) GetValidator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidator", reflect.TypeOf((*MockIDatabase)(nil).GetValidator), arg0)
}

// GetVoucherByCode mocks base method.
func (m *MockIDatabase) GetVoucherByCode(code string) (entity.Voucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVoucherByCode", code)
	ret0, _ := ret[0].(entity.Voucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVoucherByCode indicates an expected call of GetVoucherByCode.
func (mr *MockIDatabaseMockRecorder) GetVoucherByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVoucherByCode", reflect.TypeOf((*MockIDatabase)(nil).GetVoucherByCode), code)
}

// GetZealyUser mocks base method.
func (m *MockIDatabase) GetZealyUser(id string) (*entity.ZealyUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZealyUser", id)
	ret0, _ := ret[0].(*entity.ZealyUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZealyUser indicates an expected call of GetZealyUser.
func (mr *MockIDatabaseMockRecorder) GetZealyUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZealyUser", reflect.TypeOf((*MockIDatabase)(nil).GetZealyUser), id)
}

// HasUser mocks base method.
func (m *MockIDatabase) HasUser(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUser", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasUser indicates an expected call of HasUser.
func (mr *MockIDatabaseMockRecorder) HasUser(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUser", reflect.TypeOf((*MockIDatabase)(nil).HasUser), id)
}

// ListVoucher mocks base method.
func (m *MockIDatabase) ListVoucher() ([]*entity.Voucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVoucher")
	ret0, _ := ret[0].([]*entity.Voucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVoucher indicates an expected call of ListVoucher.
func (mr *MockIDatabaseMockRecorder) ListVoucher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVoucher", reflect.TypeOf((*MockIDatabase)(nil).ListVoucher))
}

// UpdateNotificationStatus mocks base method.
func (m *MockIDatabase) UpdateNotificationStatus(id uint, status entity.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationStatus indicates an expected call of UpdateNotificationStatus.
func (mr *MockIDatabaseMockRecorder) UpdateNotificationStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationStatus", reflect.TypeOf((*MockIDatabase)(nil).UpdateNotificationStatus), id, status)
}

// UpdateZealyUser mocks base method.
func (m *MockIDatabase) UpdateZealyUser(id, txHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZealyUser", id, txHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZealyUser indicates an expected call of UpdateZealyUser.
func (mr *MockIDatabaseMockRecorder) UpdateZealyUser(id, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZealyUser", reflect.TypeOf((*MockIDatabase)(nil).UpdateZealyUser), id, txHash)
}
