// Code generated by command-generator. DO NOT EDIT.
package market

import (
	"github.com/pagu-project/pagu/internal/engine/command"
)

type marketSubCmds struct {
	subCmdPrice *command.Command
}

func (c *MarketCmd) buildSubCmds() *marketSubCmds {
	subCmdPrice := &command.Command{
		Name:           "price",
		Help:           "Shows the latest price of PAC coin across different markets",
		Handler:        c.priceHandler,
		ResultTemplate: "Xeggex Price: **{{.xeggexPrice}} USDT**\nhttps://xeggex.com/market/PACTUS_USDT\n\nAzbit Price: **{{.azbitPrice}} USDT**\nhttps://azbit.com/exchange/PAC_USDT",
	}

	return &marketSubCmds{
		subCmdPrice: subCmdPrice,
	}
}

func (c *MarketCmd) buildMarketCommand() *command.Command {
	marketCmd := &command.Command{
		Emoji:       "📈",
		Name:        "market",
		Help:        "Commands for managing market",
		SubCommands: make([]*command.Command, 0),
	}

	c.marketSubCmds = c.buildSubCmds()

	marketCmd.AddSubCommand(c.subCmdPrice)

	return marketCmd
}
