// Code generated by command-generator. DO NOT EDIT.
package market

import (
	"github.com/pagu-project/pagu/internal/engine/command"
	"github.com/pagu-project/pagu/internal/entity"
)

type marketSubCmds struct {
	subCmdPrice *command.Command
}

func (c *MarketCmd) buildSubCmds() *marketSubCmds {
	subCmdPrice := &command.Command{
		Name:           "price",
		Help:           "Shows the latest price of PAC coin across different markets",
		Handler:        c.priceHandler,
		ResultTemplate: "\nTradeogre Price: **{{.tradeOgre}} USDT**\n[Trade Ogre](https://tradeogre.com/exchange/PAC-USDT)\n\nAzbit Price: **{{.azbitPrice}} USDT**\n[Azbit](https://azbit.com/exchange/PAC_USDT)\n",
		TargetBotIDs:   entity.AllBotIDs(),
	}

	return &marketSubCmds{
		subCmdPrice: subCmdPrice,
	}
}

func (c *MarketCmd) buildMarketCommand(botID entity.BotID) *command.Command {
	marketCmd := &command.Command{
		Name:         "market",
		Emoji:        "📈",
		Active:       true,
		Help:         "Commands to check market and price of PAC coin",
		SubCommands:  make([]*command.Command, 0),
		TargetBotIDs: entity.AllBotIDs(),
	}

	c.marketSubCmds = c.buildSubCmds()

	marketCmd.AddSubCommand(botID, c.subCmdPrice)

	return marketCmd
}
