services:
  pagu_discord:
    image: pagu:${DEPLOY_TAG}
    container_name: pagu_discord_${DEPLOY_TAG}
    command: "./pagu -c /pagu/config_discord.${DEPLOY_TAG}.yml run"
    networks:
      - pagu_network
    volumes:
      - ${HOME}/pagu:/pagu
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pagu_moderator:
    image: pagu:${DEPLOY_TAG}
    container_name: pagu_moderator_${DEPLOY_TAG}
    command: "./pagu -c /pagu/config_moderator.${DEPLOY_TAG}.yml run"
    networks:
      - pagu_network
    volumes:
      - ${HOME}/pagu:/pagu
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pagu_telegram:
    image: pagu:${DEPLOY_TAG}
    container_name: pagu_telegram_${DEPLOY_TAG}
    command: "./pagu -c /pagu/config_telegram.${DEPLOY_TAG}.yml run"
    networks:
      - pagu_network
    volumes:
      - ${HOME}/pagu:/pagu
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pagu-volume:

networks:
  pagu_network:
    external: true

