services:
  pagu-db:
    image: mysql:8.0.40-debian
    hostname: pagu-db
    environment:
      MYSQL_DATABASE: pagu
      MYSQL_ROOT_PASSWORD: ${PAGU_DB_ROOT_PASSWORD}
      MYSQL_USER:  ${PAGU_DB_USER}
      MYSQL_PASSWORD:  ${PAGU_DB_USER_PASSWORD}
    container_name: pagu-db
    volumes:
      - ${HOME}/mysql_data:/var/lib/mysql
    networks:
      - pagu-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", pagu-db]
      timeout: 5s
      retries: 10

  pagu-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: pagu-db
    container_name: pagu-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      pagu-db:
        condition: service_healthy
    networks:
      - pagu-network

  pagu-discord-mainnet:
    image: pagu-discord:stable
    container_name: pagu-discord-mainnet
    networks:
      pagu-network:
    depends_on:
      - pagu-phpmyadmin
    volumes:
      - ${HOME}/pagu-discord-mainnet:/pagu

  pagu-discord-staging:
    image: pagu-discord:latest
    container_name: pagu-discord-staging
    networks:
      pagu-network:
    depends_on:
      - pagu-phpmyadmin
    volumes:
      - ${HOME}/pagu-discord-staging:/pagu

  pagu-discord-testnet:
    image: pagu-discord:latest
    container_name: pagu-discord-testnet
    networks:
      pagu-network:
    depends_on:
      - pagu-phpmyadmin
    volumes:
      - ${HOME}/pagu-discord-testnet:/pagu

  pagu-discord-moderator:
    image: pagu-discord:stable
    container_name: pagu-discord-moderator
    networks:
      pagu-network:
    depends_on:
      - pagu-phpmyadmin
    volumes:
      - ${HOME}/pagu-discord-moderator:/pagu

  pagu-telegram-mainnet:
    image: pagu-telegram:stable
    container_name: pagu-telegram-mainnet
    networks:
      pagu-network:
    depends_on:
      - pagu-phpmyadmin
    volumes:
      - ${HOME}/pagu-telegram-mainnet:/pagu

volumes:
  pagu-volume:

networks:
  pagu-network:
