build-cli-container:
	BUILDKIT_PROGRESS=plain docker compose build pagu-cli

build-discord-container:
	BUILDKIT_PROGRESS=plain docker compose build pagu-discord

build-cli-telegram:
	BUILDKIT_PROGRESS=plain docker compose build pagu-telegram

force-run:
	BUILDKIT_PROGRESS=plain docker compose up -d --force-recreate