# List of Pactus nodes that Pagu can connect to for retrieving information about the Pactus network.
# These nodes must have public gRPC endpoints.
nodes:
  - "bootstrap1.pactus.org:50051"
  - "bootstrap2.pactus.org:50051"
  - "bootstrap3.pactus.org:50051"
  - "bootstrap4.pactus.org:50051"

# Wallet configuration
wallet:
  mainnet-full:
    address: pc1... # Wallet address for transactions
    path: ./config/wallet.sample.full # Path to wallet file
    password: # Wallet file password

  mainnet-neutered:
    address: pc1...
    path: ./config/wallet.sample.neutered

# Phoenix (TestNet) configuration
phoenix:
  faucet_amount: 5 # Amount of coins sent when the faucet is used

# Database configuration
database:
  url: "sqlite:db.sqlite" # Database type and connection string

# Discord integration configuration
discord:
  guild_id:
  token:

moderator:
  guild_id:
  token:

# Telegram integration configuration
telegram:
  bot_token:

# Logger configuration
logger:
  level: "info" # Logging level (debug, info, warn, error, or fatal)
  filename: "pagu.log" # Log file name
  max_size: 10 # Maximum log file size (MB)
  max_backups: 10 # Maximum backup log files to retain
  compress: true # Compress old log files
  targets: [file, console] # Logging targets (file, console, or both)
