bot_name: "Pagu-Development"

# Specify the network the bot will use: Mainnet, Testnet, or Localnet.
network: "Mainnet"

# Pactus clients
local_node: "bootstrap1.pactus.org:50051" # Address of the local Pactus node for direct communication.

# List of Pactus nodes Pagu can connect to for information.
# These nodes must have public gRPC endpoints.
network_nodes:
  [
    "bootstrap1.pactus.org:50051",
    "bootstrap2.pactus.org:50051",
    "bootstrap3.pactus.org:50051",
    "bootstrap4.pactus.org:50051",
  ]

# Wallet configuration
#
# Use the Pactus Wallet command-line tool to create a wallet.
# For detailed instructions, visit:
# https://docs.pactus.org/tutorials/pactus-wallet/
#
# The sample wallet here is neutered, which means it is read-only and can't be used to sign any transactions.
# You can create a full wallet and replace it.
wallet:
  # This is the Pagu wallet address to send transactions
  address: pc1re5uxrtdve6gama8veqt0ttz5vgfne73w9e03w6

  # Path to the wallet file.
  path: ./config/wallet.sample.neutered

  # Password for the wallet file.
  password:

  # The fee to be paid for each transaction sent by Pagu.
  fee: 0.01

# Phoenix (TestNet) configuration
phoenix:
  # Number of coins to send when the faucet is used.
  faucet_amount: 5

# Database configuration
database:
  # The database URL specifies the database type and connection string.
  # Pagu supports MySQL and SQLite.
  url: "sqlite:db.sqlite"

# Discord integration configuration
# Set appropriate values to integrate Pagu with your Discord server.
discord:
  # Discord bot application token.
  token:

  # Discord server ID where the bot will operate.
  guild_id:

# Telegram integration configuration
# Set appropriate values to integrate Pagu with your Telegram account.
telegram:
  # Telegram bot token for authentication.
  bot_token:

# NowPayments configuration.
now_payments:
  webhook:
  listen_port:
  api_token:
  ipn_secret:
  api_url: "https://api.nowpayments.io"
  payment_url: "https://nowpayments.io"
  username:
  password:

# Logger configuration
logger:
  level: "info" # Logging level: debug, info, warn, error, or fatal.
  filename: "pagu.log" # Name of the log file.
  max_size: 10 # Maximum size (in MB) of the log file before rotation.
  max_backups: 10 # Maximum number of backup log files to retain.
  compress: true # Compress old log files.
  targets: [file, console] # Logging targets: file, console, or both.