bot_name: ""
network: "Localnet"

# Pactus clients
local_node: "localhost:50051"
network_nodes: ["localhost:50051"]

# Wallet
wallet:
  enable: true
  address: "wallet_address"
  rpc: "localhost:50051"
  path: "./local/net1/wallets/main_wallet"
  password: "wallet_password"

# Phoenix TestNet
phoenix:
  network_nodes: ["localhost:50052"]
  faucet_amount: 5

#Database
database:
  url: ""

# Discord
discord:
  token: 0
  guild_id: 0

# gRPC
grpc:
  listen: "localhost:9090"

# HTTP
http:
  listen: "localhost:3000"

# Logger
logger:
  level: "info"
  filename: "pagu.log"
  max_size: 10
  max_backups: 10
  compress: true
  targets: [file, console]

telegram:
  bot_token: "token"
  chat_id: 0
  group_link: "https://t.me/pactuschat"
