// Code generated by command-generator. DO NOT EDIT.
package phoenix

import (
	"github.com/pagu-project/pagu/internal/engine/command"
)

const argNameFaucetAddress = "address"

type phoenixSubCmds struct {
	subCmdFaucet *command.Command
	subCmdWallet *command.Command
}

func (c *PhoenixCmd) buildSubCmds() *phoenixSubCmds {
	subCmdFaucet := &command.Command{
		Name:           "faucet",
		Help:           "Get tPAC Coins on Phoenix Testnet for Testing your code or project",
		Handler:        c.faucetHandler,
		ResultTemplate: "You got {{.amount}} tPAC on Phoenix Testnet!\n\nhttps://phoenix.testnet.pac.network/tx/{{.txHash}}\n",
		Args: []*command.Args{
			{
				Name:     "address",
				Desc:     "Your testnet address [example: tpc1z...]",
				InputBox: command.InputBoxText,
				Optional: false,
			},
		},
	}
	subCmdWallet := &command.Command{
		Name:           "wallet",
		Help:           "Show the faucet wallet balance",
		Handler:        c.walletHandler,
		ResultTemplate: "Pagu Phoenix wallet\n\nAddress: {{.address}}\nBalance: {{.balance}}\n",
	}

	return &phoenixSubCmds{
		subCmdFaucet: subCmdFaucet,
		subCmdWallet: subCmdWallet,
	}
}

func (c *PhoenixCmd) buildPhoenixCommand() *command.Command {
	phoenixCmd := &command.Command{
		Emoji:       "🛠️",
		Name:        "phoenix",
		Help:        "Phoenix Testnet tools and utils for developers",
		SubCommands: make([]*command.Command, 0),
	}

	c.phoenixSubCmds = c.buildSubCmds()

	phoenixCmd.AddSubCommand(c.subCmdFaucet)
	phoenixCmd.AddSubCommand(c.subCmdWallet)

	return phoenixCmd
}
