// Code generated by command-generator. DO NOT EDIT.
package phoenix

import (
	"github.com/pagu-project/pagu/internal/engine/command"
	"github.com/pagu-project/pagu/internal/entity"
)

const argNameFaucetAddress = "address"

type phoenixSubCmds struct {
	subCmdHealth *command.Command
	subCmdStatus *command.Command
	subCmdFaucet *command.Command
	subCmdWallet *command.Command
}

func (c *PhoenixCmd) buildSubCmds() *phoenixSubCmds {
	subCmdHealth := &command.Command{
		Name:            "health",
		Help:            "Check the network health status",
		Handler:         c.healthHandler,
		ResultTemplate:  "**Network is {{.Status}}**\n**Current Time**: {{.CurrentTime}}\n**Last Block Time**: {{.LastBlockTime}}\n**Time Difference**: {{.TimeDiff}}\n**Last Block Height**: {{.LastBlockHeight}}\n",
		TargetBotIDs:    entity.AllBotIDs(),
		TargetUserRoles: entity.AllUserRoles(),
	}
	subCmdStatus := &command.Command{
		Name:            "status",
		Help:            "View network statistics",
		Handler:         c.statusHandler,
		ResultTemplate:  "**Network Name**: {{.NetworkName}}\n**Connected Peers**: {{.ConnectedPeers}}\n**Validator Count**: {{.ValidatorsCount}}\n**Account Count**: {{.AccountsCount}}\n**Current Block Height**: {{.CurrentBlockHeight}}\n**Total Power**: {{.TotalPower}} tPAC\n**Total Committee Power**: {{.TotalCommitteePower}} tPAC\n\n> Note📝: This info is from a random network node. Some data may not be consistent.\n",
		TargetBotIDs:    entity.AllBotIDs(),
		TargetUserRoles: entity.AllUserRoles(),
	}
	subCmdFaucet := &command.Command{
		Name:            "faucet",
		Help:            "Get tPAC test coins on Phoenix Testnet for testing your project",
		Handler:         c.faucetHandler,
		ResultTemplate:  "You received {{.amount}} tPAC on Phoenix Testnet!\n\nhttps://phoenix.pacviewer.com/transaction/{{.txHash}}\n",
		TargetBotIDs:    entity.AllBotIDs(),
		TargetUserRoles: entity.AllUserRoles(),
		Args: []*command.Args{
			{
				Name:     "address",
				Desc:     "Your testnet address [example: tpc1z...]",
				InputBox: command.InputBoxText,
				Optional: false,
			},
		},
	}
	subCmdWallet := &command.Command{
		Name:            "wallet",
		Help:            "Show the Pagu Phoenix (Faucet) wallet info",
		Handler:         c.walletHandler,
		ResultTemplate:  "Pagu Phoenix Wallet:\n\n**Address**: {{.address}}\n**Balance**: {{.balance}}\n",
		TargetBotIDs:    entity.AllBotIDs(),
		TargetUserRoles: entity.AllUserRoles(),
	}

	return &phoenixSubCmds{
		subCmdHealth: subCmdHealth,
		subCmdStatus: subCmdStatus,
		subCmdFaucet: subCmdFaucet,
		subCmdWallet: subCmdWallet,
	}
}

func (c *PhoenixCmd) buildPhoenixCommand(botID entity.BotID) *command.Command {
	phoenixCmd := &command.Command{
		Name:            "phoenix",
		Emoji:           "🐦",
		Active:          true,
		Help:            "Commands for working with Phoenix Testnet",
		SubCommands:     make([]*command.Command, 0),
		TargetBotIDs:    entity.AllBotIDs(),
		TargetUserRoles: entity.AllUserRoles(),
	}

	c.phoenixSubCmds = c.buildSubCmds()

	phoenixCmd.AddSubCommand(botID, c.subCmdHealth)
	phoenixCmd.AddSubCommand(botID, c.subCmdStatus)
	phoenixCmd.AddSubCommand(botID, c.subCmdFaucet)
	phoenixCmd.AddSubCommand(botID, c.subCmdWallet)

	return phoenixCmd
}
