name: Lint and format check
permissions:
  contents: read

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Check linting and formatting
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.2
